In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn

In [2]:
df = pd.read_csv('fallLoaded.csv', header=None)

In [3]:
df.tail()

0          1          2          3          4          5   \
73   6.024278  15.849229  15.849229   9.335976  10.030893  10.030893   
74  12.250629  12.250629   9.261653   9.920954   9.920954  11.718920   
75   8.777485  10.548592  12.459223  12.459223   9.367245   9.367245   
76  10.576114   6.792334   6.792334  23.156575  23.156575   9.470008   
77   9.272288   8.414165   8.414165  11.613018  11.613018   8.527611   

           6          7          8          9  ...         41         42  \
73  12.364905  12.364905  13.431830  13.431830 ...   9.582777  10.993308   
74  11.718920  10.300500  10.300500   9.653787 ...  11.864809   9.306073   
75   5.340309   5.340309  20.788011  20.788011 ...   4.622599   6.994394   
76   9.470008   9.958758   9.958758  10.020382 ...   8.129599  17.376547   
77   8.527611   8.939048   8.939048   8.883479 ...   9.448011   9.448011   

           43         44         45        46         47         48  \
73   4.721731   4.721731   4.721731  4.721731   4.721731  31.766251   
74   6.182304   6.182304   6.062609  6.062609  18.449781  18.449781   
75   6.994394  17.892497  17.892497  9.880317   9.880317  11.401720   
76  17.376547   9.581752   9.581752  9.844602   9.844602  10.913039   
77   9.448011   9.448011   9.448011  9.448011   9.448011   9.448011   

           49  50  
73  31.766251   0  
74   8.777485   0  
75  11.401720   0  
76  10.913039   0  
77   9.448011   0  

[5 rows x 51 columns]

In [4]:
x = df.iloc[:,0:50]
x

0          1          2          3          4          5   \
0    9.902219   9.906456   9.906456  10.008936  10.008936   9.987972   
1   13.224596   7.249333   7.249333  16.051785  16.051785   8.427756   
2    9.867024   9.736402   9.736402   9.722813   9.722813   9.908484   
3    9.943455   9.943455   9.966316   9.966316  10.270151  10.270151   
4   10.030883  11.207846  11.207846   9.054966   9.054966   8.484421   
5    9.661216   9.724917   9.724917   9.806537   9.835983   9.835983   
6    9.756062   9.756062   9.785751   9.889422   9.889422  10.577631   
7   10.859242  10.361045  10.361045   9.964713   9.964713   9.809586   
8   10.002518   9.627655   9.627655   9.827565   9.827565  10.225014   
9    8.926137   8.690378  15.742633  15.742633  10.294695  10.294695   
10  10.327553  10.327553  10.513106  10.746774  10.746774   9.231640   
11   9.962900   9.740819  10.220652  10.220652  10.070998  10.070998   
12   9.812225   9.734156   9.734156   9.800849   9.800849  10.315023   
13   9.794758   9.807505   9.807505   9.778441   9.778441   9.808174   
14   9.472159  11.131434  11.131434  12.152709  12.152709  10.189268   
15   9.776673   9.743424   9.743424   9.712701   9.712701   9.777995   
16   9.838284   9.851076   9.851076   9.908229   9.847185   9.847185   
17   9.812547   9.907789   9.907789   9.849336  10.172729  10.172729   
18  12.743549  11.537331  11.537331   9.851339   9.851339   9.484112   
19   9.913659   9.913659   9.881985   9.881985   9.947760   9.947760   
20  11.732033  11.732033   9.195440   9.195440  10.008715  10.008715   
21   9.696816   9.696816   9.854296   9.854296   9.691488  10.219557   
22   9.747327   9.760970   9.760970   9.930003   9.930003  10.091661   
23   9.261447   9.908850   9.908850  10.321032  10.321032   9.724762   
24   9.747089   9.747089   9.939002   9.939002  10.075428  10.090222   
25   9.936764   9.755223   9.755223   9.783526   9.783526   9.801053   
26   9.662861  11.660051  11.660051   8.659940   8.659940  10.647872   
27  10.141292   9.974173   9.974173   9.765219   9.765219   9.831658   
28  10.203062  10.203062   9.587580   9.587580   7.695406   7.695406   
29   9.907311   9.845867   9.845867   9.886710   9.886710   9.913665   
..        ...        ...        ...        ...        ...        ...   
48  10.280701  11.279083  11.279083   9.865190   9.865190  10.862488   
49   7.709507  14.041992  14.041992   9.447525   9.447525  13.560761   
50   9.938677  10.219266  10.219266  10.259322  10.259322  10.174244   
51  10.261551  10.584763  10.584763  10.307037  10.307037   9.129487   
52  10.731577   7.524444   7.524444   9.811783   9.811783   9.524362   
53   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
54   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
55   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
56   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
57   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
58   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
59   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
60   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
61   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
62   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
63   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
64   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
65   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
66   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
67   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
68   9.976600   9.976600   9.976600   9.976600   9.976600   9.976600   
69  10.773521  11.200271  11.200271   7.299877   7.299877  13.834530   
70   9.097050   9.097050   9.312043   9.312043   9.054542   9.244106   
71  10.554296  11.882367  11.882367   7.875253   6.

In [7]:
y = df.iloc[:,50:51]

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=0)

In [15]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(multi_class=multi_clas)

In [16]:
logisticRegr.fit(x, y)

/usr/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [17]:
predictions = logisticRegr.predict(x_test)

In [12]:
predictions

array([1, 1, 1, 0, 0, 1, 0, 1])

In [13]:
y_test

50
49   0
27   1
30   1
63   0
45   0
69   0
73   0
75   0

In [18]:
score = logisticRegr.score(x_test, y_test)
print(score)
single =  df.iloc[:1,0:50]

1.0


In [56]:
yboi = logisticRegr.predict(single)

In [57]:
yboi

array([1])

In [58]:
single = df.iloc[40:41,0:50]
yboi = logisticRegr.predict(single)
yboi

array([0])

In [19]:
import pickle

In [22]:
filename = 'finalized_fall_model.sav'
pickle.dump(logisticRegr, open(filename, 'wb'))