In [1]:
import pickle

In [2]:
filename = 'finalized_fall_model.sav'

In [3]:
loaded_model = pickle.load(open(filename, 'rb'))

In [11]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('fallLoaded.csv', header=None)

In [21]:
x = df.iloc[0:1,0:50]
xl = np.array(x)
xl

array([[ 9.90221873,  9.90645649,  9.90645649, 10.00893578, 10.00893578,
         9.98797178,  9.98797178,  9.91243758, 10.01337141, 10.01337141,
         9.6050221 ,  9.6050221 , 11.31818349, 11.31818349,  7.71707559,
         7.71707559, 13.35813706,  8.11294343,  8.11294343, 10.92726144,
        10.92726144, 23.15805832, 23.15805832, 14.44817493, 14.44817493,
        11.11240535, 13.57273865, 13.57273865, 15.40828054, 15.40828054,
        11.02673154, 11.02673154, 13.13009087, 13.13009087,  9.97082488,
         9.97082488, 10.3065169 , 11.16134403, 11.16134403, 11.69285073,
        11.69285073, 13.6440854 , 13.6440854 , 10.16360358, 10.16360358,
         7.57784304,  7.57784304, 14.2563333 , 11.28179757, 11.28179757]])

In [13]:
loaded_model.predict(xl)

array([1])

In [24]:
x4= np.array([[1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10]]);

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
loaded_model.predict(x4)

array([0])